version: "3.2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: wurstmeister/kafka
    ports:
     - "9093:9093"
    environment:
      - "HOSTNAME_COMMAND=>-
          docker info | grep Name: | cut -d' ' -f 2"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost.localdomain:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - "KAFKA_CREATE_TOPICS=>-
          events:3:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      - "HOSTNAME_COMMAND=docker info | grep Name: >-
          | cut -d' ' -f 2"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost.localdomain:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9095:9095"
    environment:
      - "HOSTNAME_COMMAND=docker info | grep Name: >-
          | cut -d' ' -f 2"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9095
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost.localdomain:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper



